[package]
name = "fire"
version = "0.5.0"
authors = ["An Long <aisk1988@gmail.com>"]
license = "BSD-2-Clause"
description = "Turn functions into command-line applications with one attribute, like Python's fire"
repository = "https://github.com/aisk/rust-fire"
documentation = "https://docs.rs/fire"
keywords = ["cli", "args", "argparse", "command-line", "fire"]
categories = ["command-line-utilities"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.66"
quote = "^1.0.32"
syn = { version = "^2.0.28", features = ["full"] }

[dev-dependencies]
tokio = { version = "^1", features = ["rt-multi-thread", "time"] }
